### ISSUE TITLE
Add attribute mapping for first name and last name

### ISSUE THREAD

**Issue by johkoenig** [nextcloud/ldap_contacts_backend#8]
Hi @blizzz,
As far as I've seen in the two tickets (I didn't check the code), you're only mapping the display name. I propose you should also map fist name and last name seperately. This allows you to distinguish more precisely in he following cases:
* Three names, for example:
    * Two first names, e.g. John Jacob Astor
    * Two last names, e.g. Felix Schulze Müller (yes, I know a person named like this and his two last names are seperated by a space)
    * Titles, e.g. Dr. John Doe
    * Nobility, e.g. Otto Graf von Bismarck

**Comment by blizzz** [comment]
We have a default mapping:

```php
private const DEFAULT_MAPPING = [
		'FN' => 'displayName',
		'EMAIL' => 'mail',
		'PHOTO' => 'jpegPhoto',
		'ADR' => 'registeredAddress',
		'TEL' => 'telephoneNumber',
		'TITLE' => 'title',
		'ORG' => 'ou',
	];
```

(https://github.com/nextcloud/ldap_contacts_backend/blob/master/lib/Service/LdapEntryToVcard.php)

which indeed only includes the display name (what FN is for). But when you configure an connection, you can add custom mappings that would include all the names you would like. Since cultures are different, and LDAPs are different, the default mapping gives a good elementary setup, anything beyond is then up to the administrator.

**Comment by LenhardErwan** [comment]
Thanks @blizzz,

@johkoenig, indeed this parameter can be easily customized in the application's configurations.

`LDAP / AD integration -> Advanced -> Directory Settings -> User Display name Field`
And in this field you can set `cn` for example which is the concatenation of first name and last name.
![image](https://user-images.githubusercontent.com/35600901/90150896-6b133b00-dd86-11ea-8c60-6f4607d45e07.png)

Example of attributes:
![image](https://user-images.githubusercontent.com/35600901/90150324-d4df1500-dd85-11ea-85df-6b9a41572994.png)

**Comment by blizzz** [comment]
this repo is not the LDAP backend, that's part of server.

**Comment by LenhardErwan** [comment]
Exactly,
my bad. But your response still helped me 😉
